name = "cnx-athletx-api"
main = "src/index.ts"
compatibility_date = "2026-02-25"
account_id = "0ccff0e0abbbf8d1395557afe2cf9a42"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "cnx-athletx-dev"
database_id = "805d023a-2d77-4aef-95eb-164a82201962"
preview_database_id = "805d023a-2d77-4aef-95eb-164a82201962"

[env.production]
name = "cnx-athletx-api"

[env.production.vars]
ALLOWED_ORIGINS = "https://cnxathletx.com,https://www.cnxathletx.com"

[[env.production.d1_databases]]
binding = "DB"
database_name = "cnx-athletx-prod"
database_id = "63f96854-8d6f-49c5-a9c3-b5e8b90f2cae"
preview_database_id = "63f96854-8d6f-49c5-a9c3-b5e8b90f2cae"

[observability]
enabled = true
